// pages/faq.js
import { useState } from 'react'
import { Box, Button, Container, Heading, Link, Text } from 'theme-ui'
import { Header } from '../views/landing'

type AccordionItemProps = {
  title: string
  children: React.ReactNode
}

const AccordionItem = ({ title, children }: AccordionItemProps) => {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <Box sx={{ mb: 3 }}>
      <Button
        onClick={() => setIsOpen(!isOpen)}
        sx={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          width: '100%',
          bg: 'secondary',
          color: 'lightgrey',
          cursor: 'pointer',
          fontSize: 2,
          py: 3,
          px: 4,
          border: 'none',
          ':focus': { outline: 'none' },
          textAlign: 'left',
        }}
      >
        <Text>{title}</Text>
        <Text>{isOpen ? '-' : '+'}</Text>
      </Button>
      {isOpen && (
        <Box sx={{ p: 3, pt: 4, color: 'white' }}>
          <Text>{children}</Text>
        </Box>
      )}
    </Box>
  )
}

type AccordionProps = {
  items: { title: string; content: React.ReactNode }[]
}

const Accordion = ({ items }: AccordionProps) => (
  <Box>
    {items.map((item, index) => (
      <AccordionItem key={index} title={item.title}>
        {item.content}
      </AccordionItem>
    ))}
  </Box>
)

const faqItems = [
  {
    title: 'What is Degen ETH?',
    content: `Degen ETH is a high-yield diversified ETH strategy index designed to sustainably outperform LST market yields. Degen ETH uses a two-token model: dgnETH, which is pegged to ETH and backed 1:1 by DeFi yield strategies, and sdgnETH, obtained by depositing dgnETH in a staking vault, which accrues all yield from dgnETH’s underlying assets.`,
  },
  {
    title:
      'What is the difference between dgnETH and sdgnETH and what can I do with them?',
    content: `Degen ETH (dgnETH) is minted by depositing ETH into select yield strategies across DeFi. While dgnETH maintains a 1:1 peg to ETH and doesn't accrue staking rewards, it can be used to earn yield onchain across the DeFi integrations listed here. Staked Degen ETH (sdgnETH) is obtained by depositing dgnETH into the staking contract, which accrues all the yield generated from dgnETH’s underlying yield strategies. This staking mechanism provides users with boosted on-chain yield without the need to actively manage multiple strategies, making it a simple option for passive yield generation.`,
  },
  {
    title: 'Where does the yield come from?',
    content: `The yield earned by Degen ETH stakers (sdgnETH) is generated from the underlying yield strategies that make up dgnETH’s collateral basket and boosted by the two-token model. All the yield generated by dgnETH’s collateral basket accrues to the staking contract —the higher the supply of dgnETH relative to sdgnETH, the higher the staking yield will be. The underlying yield strategies backing dgnETH can be audited onchain at any time here.`,
  },
  {
    title: 'What is Reserve?',
    content: (
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
        <Box>
          Reserve Protocol is a free, permissionless platform on Ethereum
          mainnet, Base, and Arbitrum to build, deploy and govern asset-backed
          currencies referred to as “RTokens.” RTokens are always 1:1
          asset-backed, allowing for permissionless minting and redemptions
          onchain.
        </Box>
        <Box>
          RTokens operate as independent DAOs governed by Reserve Rights (RSR)
          stakers. RSR can be staked on RTokens, where it serves two roles: (1)
          Overcollateralization, staked RSR receives a portion of the collateral
          basket yield in exchange for being first capital-at-risk in cases of
          collateral default; and (2) Governance, staked RSR proposes and votes
          on changes in RToken configuration (i.e. changes to RToken collateral
          basket changes or revenue distribution).
        </Box>
        <Box>
          The Reserve protocol has been live on Ethereum, Base, and Arbitrum
          collectively for over a year now with no security incidents. 8{' '}
          <Link
            href="https://github.com/reserve-protocol/protocol/tree/master/audits"
            target="_blank"
            sx={{ display: 'inline', color: 'gray' }}
          >
            major audits
          </Link>{' '}
          have been completed and a{' '}
          <Link
            href="https://immunefi.com/bug-bounty/reserve/"
            target="_blank"
            sx={{ display: 'inline', color: 'gray' }}
          >
            $5M ImmuneFi bug bounty
          </Link>{' '}
          continues to contribute to the safety. More information can be found
          here.
        </Box>
        <Box>
          Degen ETH is an RToken built on Reserve protocol and governed by RSR
          stakers, who can propose changes to the underlying yield strategies
          and yield distribution. dgnETH can be instantly redeemed onchain for
          its underlying assets, which can be audited at any time{' '}
          <Link
            href="https://app.reserve.org/ethereum/token/0x005f893ecd7bf9667195642f7649da8163e23658/overview"
            target="_blank"
            sx={{ display: 'inline', color: 'gray' }}
          >
            here
          </Link>
          .
        </Box>
      </Box>
    ),
  },
]

const FAQPage = () => {
  return (
    <Container
      variant="wrapper"
      pb={4}
      sx={{ maxWidth: [1300, 1700], width: ['95%', '95%', '90%'] }}
    >
      <Box
        p={[3, 5]}
        mb={4}
        sx={{
          backgroundColor: 'primary',
          borderRadius: '0px 0px 16px 16px',
          minHeight: ['auto', 'auto', 120],
          flexDirection: 'column',
          overflow: 'hidden',
          position: 'relative',
        }}
      >
        <Header />
        <Text
          variant="title"
          sx={{
            mt: 4,
            mb: 1,
            fontSize: [4, 6],
            fontWeight: 'bold',
            lineHeight: ['42px', '62px', '62px', '62px', '82px'],
            textAlign: 'center',
          }}
        >
          Frequently Asked Questions
        </Text>
      </Box>
      <Accordion items={faqItems} />
    </Container>
  )
}

export default FAQPage
