import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box, Card, Flex, Link, Text } from 'theme-ui'
import RTokenZapIssuance from '../components/zap/RTokenZapIssuance'
import Brand from '../components/icons/Brand'
import ConnectButton from '../components/ConnectButton'

{
  /* <Head>
<title>RainbowKit App</title>
<meta
  content="Generated by @rainbow-me/create-rainbowkit"
  name="description"
/>
<link href="/favicon.ico" rel="icon" />
</Head> */
}

{
  /* <ConnectButton /> */
}

const Header = () => {
  return (
    <Box
      sx={{
        backgroundColor: '#181818',
      }}
      p={4}
      variant="layout.verticalAlign"
    >
      <Brand />
      <Box mx="auto" />
      <ConnectButton />
    </Box>
  )
}

const StakingAPY = () => {
  return (
    <Card sx={{ flexGrow: 1, position: 'relative' }}>
      <Text>Staking APY</Text>
      <Box sx={{ position: 'absolute', bottom: 16 }}>
        <Text variant="hero">48%</Text>
        <Text variant="accent">320%</Text> <Text variant="muted">30d avg</Text>
      </Box>
    </Card>
  )
}

const Balances = () => {
  return (
    <Card sx={{ flexGrow: 1 }}>
      <Text>Your dgnETH</Text>
      <Box
        mt={2}
        p={2}
        sx={{ borderRadius: '8px', backgroundColor: 'background' }}
      >
        <Flex>
          <Text>In wallet</Text>
          <Text ml="auto">$12K</Text>
        </Flex>
        <Flex>
          <Text variant="accent">4.2</Text>
          <Text variant="muted" ml="auto">
            4.5 ETH
          </Text>
        </Flex>
        <Flex mt={3}>
          <Text>Staked</Text>
          <Text ml="auto">$12K</Text>
        </Flex>
        <Flex>
          <Text>12</Text>
          <Text variant="muted" ml="auto">
            13 ETH
          </Text>
        </Flex>
      </Box>
    </Card>
  )
}

const Supply = () => {
  return (
    <Card>
      <Text>dgnETH Supply</Text>
    </Card>
  )
}

const Earnings = () => {
  return (
    <Card mt={3}>
      <Box sx={{ gap: 2 }} variant="layout.verticalAlign">
        <Text>Your earnings</Text>
        <Text ml="auto" variant="muted">
          12K
        </Text>
        <Text variant="accent">+0.8 dgnETH</Text>
      </Box>
    </Card>
  )
}

const Overview = () => {
  return (
    <Box
      px={3}
      py={4}
      sx={{
        width: 240,
        borderLeft: '1px solid',
        flexShrink: 0,
        borderColor: 'secondary',
      }}
    >
      <Text mb="1" variant="bold">
        Big boy ETH yield
      </Text>
      <Text variant="muted">
        dgnETH gives you exposure to top yield strategies across DeFi
      </Text>
    </Box>
  )
}

const ActionContainer = () => {
  return (
    <Flex
      sx={{
        flexGrow: 1,
        border: '3px solid',
        borderColor: 'secondary',
        borderRadius: '16px',
        backgroundColor: 'cardAlternative',
      }}
    >
      <RTokenZapIssuance style={{ flexGrow: 1 }} />
      <Overview />
    </Flex>
  )
}

const Sidebar = () => {
  return (
    <Box ml="4" sx={{ position: 'relative', width: 150 }}>
      <Box
        mt="4"
        as="ul"
        sx={{ margin: 0, padding: 0, li: { listStyle: 'none' } }}
      >
        <Box as="li" sx={{ color: 'primary', fontWeight: 'bold' }}>
          Minting
        </Box>
        <Box as="li" mt={3}>
          Staking
        </Box>
      </Box>
      <Box sx={{ position: 'absolute', bottom: 16 }}>
        <Link>Earn</Link>

        <Link>Learn more</Link>
      </Box>
    </Box>
  )
}

const Home: NextPage = () => {
  return (
    <Box variant="layout.wrapper">
      <Header />
      <Flex p={4} sx={{ gap: 3 }}>
        <StakingAPY />
        <Balances />
        <Box sx={{ flexGrow: 1.5 }}>
          <Supply />
          <Earnings />
        </Box>
      </Flex>
      <Card p={0} mx={4} sx={{ display: 'flex' }}>
        <Sidebar />
        <ActionContainer />
      </Card>
    </Box>
  )
}

export default Home
