import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box } from 'theme-ui'
import RTokenZapIssuance from '../components/zap/RTokenZapIssuance'

{
  /* <Head>
<title>RainbowKit App</title>
<meta
  content="Generated by @rainbow-me/create-rainbowkit"
  name="description"
/>
<link href="/favicon.ico" rel="icon" />
</Head> */
}

{
  /* <ConnectButton /> */
}

const Home: NextPage = () => {
  return (
    <Box>
      hola
      <RTokenZapIssuance />
    </Box>
  )
}

export default Home
